### PR TITLE
master-lrqa-52148

### PR DESCRIPTION
**Pull request by Jeremy-Ch**
https://issues.liferay.com/browse/LRQA-52148

### CODE REVIEW

**Comment by Jeremy-Ch** [comment]
ci:test:sf

**Comment by liuxingye** [comment]
@Jeremy-Ch Edited your commit message to "Change display style first before checking box"

**Comment by liuxingye** [comment]
@Jeremy-Ch  Edited your commit message, see the changes here https://github.com/brianchandotcom/liferay-portal/pull/78448

**Comment by liuxingye** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/78448

**Pull request closed without merging**
