### PR TITLE
LPS-149394 | master

### PR DESCRIPTION
**Pull request by WYZ-Issac**
https://issues.liferay.com/browse/LPS-149394

### CODE REVIEW

**Comment by WYZ-Issac** [comment]
ci:test:sf

**Comment by WYZ-Issac** [comment]
ci:test:sf

**Comment by liuxingye** [comment]
Hi @WYZ-Issac please send a new PR with following changes, we can split the macros one to 2 commits

1. Send the deleted macros together 
2. Send the assert macro independently

Thanks.

**Comment by liuxingye** [comment]
See https://github.com/liuxingye/liferay-portal/pull/537

**Pull request closed without merging**
