### PR TITLE
master-lrqa-51650

### PR DESCRIPTION
**Pull request by Jeremy-Ch**
https://issues.liferay.com/browse/LRQA-51650

### CODE REVIEW

**Comment by Jeremy-Ch** [comment]
ci:test:sf

**Comment by Jeremy-Ch** [comment]
ci:test:wiki

**Comment by liuxingye** [comment]
@Jeremy-Ch 
We'd better use the existing methods to assert wiki page title, see changes here: https://github.com/brianchandotcom/liferay-portal/pull/77701

**Comment by liuxingye** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/77701

**Pull request closed without merging**
