### PR TITLE
master-lrqa-57100

### PR DESCRIPTION
**Pull request by Jeremy-Ch**
https://issues.liferay.com/browse/LRQA-57100
https://issues.liferay.com/browse/LRQA-56928

### CODE REVIEW

**Comment by Jeremy-Ch** [comment]
ci:test:sf

**Comment by Jeremy-Ch** [comment]
ci:test:sf

**Comment by Jeremy-Ch** [comment]
ci:test:sf

**Comment by Jeremy-Ch** [comment]
ci:test:sf

**Comment by liuxingye** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/86826

**Pull request closed without merging**
