### PR TITLE
master-qa-41213

### PR DESCRIPTION
**Pull request by liulukiwi**
https://issues.liferay.com/browse/LRQA-41213

### CODE REVIEW

**Comment by liulukiwi** [comment]
ci:test:sf

**Comment by liulukiwi** [comment]
ci:test:relevant

**Comment by liuxingye** [comment]
No test changes needed :)

**Comment by liuxingye** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/62539

**Pull request closed without merging**
