### PR TITLE
master-lps-116781

### PR DESCRIPTION
**Pull request by Jeremy-Ch**
https://issues.liferay.com/browse/LPS-116781

### CODE REVIEW

**Comment by Jeremy-Ch** [comment]
ci:test:sf

**Comment by liuxingye** [comment]
https://github.com/liferay-lima/liferay-portal/pull/525

**Comment by liuxingye** [comment]
ci:forward

**Comment by liuxingye** [comment]
ci:stop

**Comment by liuxingye** [comment]
ci:stop

**Comment by liuxingye** [comment]
ci:test:sf

**Comment by liuxingye** [comment]
Pull request submitted to https://github.com/liferay-lima/liferay-portal/pull/527

**Pull request closed without merging**
