### PR TITLE
master-lrqa-57257

### PR DESCRIPTION
**Pull request by Jeremy-Ch**
https://issues.liferay.com/browse/LRQA-57257
https://issues.liferay.com/browse/LRQA-57272
https://issues.liferay.com/browse/LRQA-57270

### CODE REVIEW

**Comment by Jeremy-Ch** [comment]
ci:test:sf

**Comment by Jeremy-Ch** [comment]
ci:test:sf

**Comment by Jeremy-Ch** [comment]
ci:test:sf

**Comment by liuxingye** [comment]
View https://github.com/liuxingye/liferay-portal/pull/224

**Pull request closed without merging**
