### PR TITLE
LPS-154463, LPS-154471, LPS-154475 | master

### PR DESCRIPTION
**Pull request by chaowang-123**
https://issues.liferay.com/browse/LPS-154463
https://issues.liferay.com/browse/LPS-154471
https://issues.liferay.com/browse/LPS-154475

### CODE REVIEW

**Comment by chaowang-123** [comment]
ci:test:sf

**Comment by chaowang-123** [comment]
ci:test:sf

**Comment by chaowang-123** [comment]
ci:test:sf

**Comment by liuxingye** [comment]
Pull request submitted to https://github.com/austinchiang/liferay-portal/pull/1402
See the changes here https://github.com/austinchiang/liferay-portal/pull/1402/commits/1ea270eaebc1158a6775be8c9257c2065e924b87

**Pull request closed without merging**
