### PR TITLE
LPS-154396 | master

### PR DESCRIPTION
**Pull request by WYZ-Issac**
https://issues.liferay.com/browse/LPS-154396

### CODE REVIEW

**Comment by WYZ-Issac** [comment]
ci:test:sf

**Comment by WYZ-Issac** [comment]
ci:test:sf

**Comment by WYZ-Issac** [comment]
ci:test:sf

**Comment by WYZ-Issac** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
@WYZ-Issac @liuxingye this was actually supposed to be an external video shortcut test but I copied some information over incorrectly. Can you please make the changes and resend? I updated the ticket description

**Comment by WYZ-Issac** [comment]
> 
Sure, I will fix the testcase and resend the commit.

**Comment by WYZ-Issac** [comment]
ci:test:sf

**Comment by liuxingye** [comment]
Submitted to https://github.com/austinchiang/liferay-portal/pull/1337
See changes [here](https://github.com/austinchiang/liferay-portal/compare/e7ff2c7824e2a0b000dba6007218b2dd95a8e3ec...2dec74b6d1bae83ee3170a2dbf2f0458c0471e36)

**Pull request closed without merging**
