### PR TITLE
master-qa-40992

### PR DESCRIPTION
**Pull request by yuwanyang**
https://issues.liferay.com/browse/LRQA-40992

### CODE REVIEW

**Comment by yuwanyang** [comment]
ci:test:sf

**Comment by yuwanyang** [comment]
ci:test:sf

**Comment by liuxingye** [comment]
@yuwanyang 

Edited your commit message to 'Update minor version'

**Comment by liuxingye** [comment]
Pushed to BChan.
[brianchandotcom#60005](https://github.com/brianchandotcom/liferay-portal/pull/60005).

**Pull request closed without merging**
