### PR TITLE
LPS-149971 | master

### PR DESCRIPTION
**Pull request by WYZ-Issac**
https://issues.liferay.com/browse/LPS-149971

### CODE REVIEW

**Comment by WYZ-Issac** [comment]
ci:test:sf

**Comment by WYZ-Issac** [comment]
ci:test:sf

**Comment by liuxingye** [comment]
Reviewing...

**Comment by liuxingye** [comment]
@WYZ-Issac 

- I think we'd better to change the file name from test.html to xss_test.html to make it clear with what we test
- For this macro **enableDirectoryIndexing**, can you rewrite it with a URL to navigate to the documents and media type in site settings. probably refer to **Ratings._openToConfigInSiteSettings**
- I think we can write a new macro like DMDocument#downloadWithDirectoryIndexing to include the steps
```
		var portalURL = PropsUtil.get("portal.url");

		Navigator.openSpecificURL(url = "${portalURL}/documents/guest/");

		AssertClick(
			key_text = "test",
			locator1 = "Link#ANY",
			value1 = "test");
```

**Comment by WYZ-Issac** [comment]
see in [https://github.com/liuxingye/liferay-portal/pull/525](https://github.com/liuxingye/liferay-portal/pull/525)

**Pull request closed without merging**
