### PR TITLE
master-lps-114337

### PR DESCRIPTION
**Pull request by Jeremy-Ch**
https://issues.liferay.com/browse/LPS-114337

### CODE REVIEW

**Comment by Jeremy-Ch** [comment]
ci:test:sf

**Comment by Jeremy-Ch** [comment]
ci:test:sf

**Comment by Jeremy-Ch** [comment]
ci:test:sf

**Comment by liuxingye** [comment]
https://github.com/liferay-lima/liferay-portal/pull/497

**Comment by liuxingye** [comment]
See changes here. https://github.com/liferay-lima/liferay-portal/pull/510/commits/08034618b9fd36c779492676856ad89c46085f82

**Comment by liuxingye** [comment]
https://github.com/liferay-lima/liferay-portal/pull/510

**Pull request closed without merging**
