### PR TITLE
master-qa-41406

### PR DESCRIPTION
**Pull request by yuwanyang**
https://issues.liferay.com/browse/LRQA-41406

### CODE REVIEW

**Comment by yuwanyang** [comment]
ci:test:sf

**Comment by liuxingye** [comment]
ci:test:sf

**Comment by liuxingye** [comment]
No test changes needed :)

**Comment by liuxingye** [comment]
Pushed to BChan.
[brianchandotcom#60110](https://github.com/brianchandotcom/liferay-portal/pull/60110).

**Pull request closed without merging**
