### PR TITLE
master-lrqa-58882

### PR DESCRIPTION
**Pull request by Jeremy-Ch**
https://issues.liferay.com/browse/LRQA-58882

### CODE REVIEW

**Comment by Jeremy-Ch** [comment]
ci:test:sf

**Comment by Jeremy-Ch** [comment]
ci:test:sf

**Comment by Jeremy-Ch** [comment]
ci:test:sf

**Comment by liuxingye** [comment]
@Jeremy-Ch 
I've moved the open depot memberships macro to the DepotNavigator file, see changes [here](https://github.com/liferay-lima/liferay-portal/pull/177/commits/31830cbb58bceea5af4b654bfa92451a4dee9421).

**Comment by liuxingye** [comment]
https://github.com/liferay-lima/liferay-portal/pull/177

**Pull request closed without merging**
