### PR TITLE
master-qa-44422

### PR DESCRIPTION
**Pull request by zhangyan0701**
https://issues.liferay.com/browse/LRQA-44422

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by liuxingye** [comment]
No test changes needed :)

**Comment by liuxingye** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/64666

**Pull request closed without merging**
