### PR TITLE
master-qa-41161

### PR DESCRIPTION
**Pull request by yuwanyang**
https://issues.liferay.com/browse/LRQA-41161

### CODE REVIEW

**Comment by yuwanyang** [comment]
ci:test:sf

**Comment by yuwanyang** [comment]
ci:test:sf

**Comment by liuxingye** [comment]
No test changes needed :)

**Comment by liuxingye** [comment]
Pushed to BChan.
[brianchandotcom#60770](https://github.com/brianchandotcom/liferay-portal/pull/60770).

**Pull request closed without merging**
