### PR TITLE
master-qa-23845

### PR DESCRIPTION
**Pull request by liulukiwi**
https://issues.liferay.com/browse/LRQA-23845

### CODE REVIEW

**Comment by brianwulbern** [comment]
@liuxingye any update on this?

**Comment by liuxingye** [comment]
@brianwulbern This PR need to redo, kiwi is working on it.

**Comment by brianwulbern** [comment]
Cool, thanks Beck.

**Comment by liuxingye** [comment]
ci:retest

**Comment by liuxingye** [comment]
No test changes needed :)

**Comment by liuxingye** [comment]
Pushed to GinsonRen.
[GinsonRen#40](https://github.com/GinsonRen/liferay-portal/pull/40)

**Comment by liuxingye** [comment]
No test changes needed :)

**Comment by liuxingye** [comment]
Pushed to GRen.
[GinsonRen#40](https://github.com/GinsonRen/liferay-portal/pull/40)

**Pull request closed without merging**
