### PR TITLE
LPS-154397 | master

### PR DESCRIPTION
**Pull request by WYZ-Issac**
https://issues.liferay.com/browse/LPS-154397

### CODE REVIEW

**Comment by WYZ-Issac** [comment]
ci:test:sf

**Comment by WYZ-Issac** [comment]
ci:test:sf

**Comment by WYZ-Issac** [comment]
ci:test:sf

**Comment by liuxingye** [comment]
@WYZ-Issac 
Pull request submitted to https://github.com/austinchiang/liferay-portal/pull/1338 and Just added a description to the test.

**Pull request closed without merging**
