### PR TITLE
master-lrqa-60111

### PR DESCRIPTION
**Pull request by Jeremy-Ch**
https://issues.liferay.com/browse/LRQA-60111

### CODE REVIEW

**Comment by Jeremy-Ch** [comment]
ci:test:sf

**Comment by Jeremy-Ch** [comment]
ci:test:sf

**Comment by Jeremy-Ch** [comment]
ci:test:sf

**Comment by liuxingye** [comment]
@Jeremy-Ch 
Edited your commit message to "Access repository again if it is not display".

**Comment by liuxingye** [comment]
https://github.com/liferay-lima/liferay-portal/pull/417

**Pull request closed without merging**
